context:
  version: "1.1.4"

package:
  name: vscode-spectral-language-server
  version: ${{ version }}

source:
  url: https://github.com/stoplightio/vscode-spectral/archive/v${{ version }}.tar.gz
  sha256: cf8e70f89071ac81b8654d7951239dc4ee6b8438bab3ab45df9bbe5dc0f796dc

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - sed
  run:
    - nodejs

tests:
  - script:
      - "spectral-language-server 2>&1 | grep -q \"Connection input stream is not set\""

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Language Server for Spectral
  homepage: https://github.com/stoplightio/vscode-spectral
  repository: https://github.com/stoplightio/vscode-spectral

extra:
  recipe-maintainers:
    - danielnachun
